### ISSUE TITLE
redirect_to appears not to work

### ISSUE THREAD

**Issue by gboone** [jekyll/jekyll-redirect-from#107]
Hello, we've been using this product for a while now and recently noticed all of our pages that use `redirect_to` are not redirecting to the expected destination. 

As an example: this URL https://18f.gsa.gov/tags/day%20in%20the%20life/ should redirect to this url: https://18f.gsa.gov/tags/day-in-the-life/ but as you can see [it generates a blank page instead](https://18f.gsa.gov/tags/day%20in%20the%20life/). Here's [the source file that generates that page](https://github.com/18F/18f.gsa.gov/blob/staging/pages/tags/day%20in%20the%20life.md).

 I haven't tested it with _all_ the pages using `redirect_to` but [`/tags/demo day/`](https://18f.gsa.gov/tags/demo%20day/) and [`/how we work/`](https://18f.gsa.gov/tags/how%20we%20work/) are also failing. 

Pages using [`redirect_from` appear to be working correctly](https://18f.gsa.gov/2016/04/07/making-more-consistent-decisions-with-design-principles-a-new-18f-guide/).

**Comment by gboone** [comment]
More background! Sleuthing by @jeremiak has shown that adding `index.html` to the end of the `permalink` you want to redirect will make it work. See, for example, this file: https://github.com/18F/18f.gsa.gov/blob/4437b6f57e1374c1d61e1638e509aac095be62aa/pages/feed.md

To correct one of the examples above:

Bad:
```
---
permalink: /tags/day in the life/
redirect_to:
  - /tags/day-in-the-life/
---
```

Good:
```
---
permalink: /tags/day in the life/index.html
redirect_to:
  - /tags/day-in-the-life/
---
```

**Comment by pathawks** [comment]
It looks like `redirect_to` only overrides the `item.content` and not any of the `item.data`.

https://github.com/jekyll/jekyll-redirect-from/blob/v0.10.0/lib/jekyll-redirect-from/redirector.rb#L30-L31

I would guess that the problem is that the page has a default layout set, and we should be turning it off here, but we are not.

No idea what adding `index.html` could be changing though.

**Comment by gboone** [comment]
> I would guess that the problem is that the page has a default layout set, and we should be turning it off here, but we are not.

Interesting, I'll give that a shot and see if it helps.

**Comment by koron** [comment]
I have investigated this as below:

* jekyll-redirect-from added `RedirectPage` for `Jekyll::Page` (not `Jekyll::Document`) which uses `redirect_to`. (see https://github.com/jekyll/jekyll-redirect-from/blob/v0.10.0/lib/jekyll-redirect-from/redirector.rb#L33)
* `RedirectPage` inherits `Jekyll::Page`
* `Jekyll::Page#destination` have returned the output filename `index.html` for URL ends with `/` in jekyll v3.0.5
*  But it returns `index` + `:extname` on same condition in jekyll v3.1.6 (**CHANGED!**)
* `extname` is determined by `Jekyll::Page#initialize`'s 4th argument `name`.
* `File.basename(item.url)` is passed as `name` (see https://github.com/jekyll/jekyll-redirect-from/blob/v0.10.0/lib/jekyll-redirect-from/redirector.rb#L26), it will be empty in some situations.
* therefore `Jekyll::Page#destination` returns filename `index` which not include `.html` extention.
* as a result of above, redirect contents is generated into `index` instead of `index.html`.

**Comment by rowleya** [comment]
I can confirm this also - the page generated is called index not index.html.  If you manually put in "index" instead of index.html, my browser downloads a file which contains the redirect html code.  Note that other page redirects work fine - it is just the name index that seems to go wrong.

**Comment by rowleya** [comment]
Incidentally, you can work around the issue by replacing the index.md with an index.html with redirect code in it:
```
<html>
    <head>
        <meta http-equiv="refresh" content="0; url=https://my-url/">
    </head>
</html>
```

**Comment by koron** [comment]
>  it is just the name index that seems to go wrong.

It is correct, but not enough.

When using `permalink: pretty`, all pages will use `index` as name (URL is ended with `/`).
So all sites which use `permalink: pretty` or similar style, are affected by this.

**Comment by koron** [comment]
I have created a patch to fix this, please check it (#108)

**Comment by ferrantim** [comment]
what is the status of this issue?  We're seeing the same problem.

**Comment by parkr** [comment]
I have not had time to look into this unfortunately. Would you be able to
setup a reproducible site in a repo quickly for me so we can debug more
easily?

Michael Ferranti <notifications@github.com> schrieb am Di., 14. Juni 2016
um 11:53:

**Comment by ferrantim** [comment]
Does it help to mention that we're using the github-pages gem?  I don't know when this stopped working exactly, but it was definately working before, so probably somethign with github-pages.

**Comment by gboone** [comment]
@parkr Not sure if this is what you mean but we're using it on 18f.gsa.gov. This URL https://18f.gsa.gov/tags/how%20we%20work/ should redirect to https://18f.gsa.gov/tags/how-we-work/ The repo is at https://github.com/18f/18f.gsa.gov
