### ISSUE TITLE
redirect_to downloads a link instead of redirecting

### ISSUE THREAD

**Issue by zfrenchee** [jekyll/jekyll-redirect-from#122]
Is this expected behavior? Try for example [fraenkel-lab.github.io/steinernet](https://fraenkel-lab.github.io/steinernet)

**Comment by parkr** [comment]
It's because it's not written as an HTML document. You should say `redirect_from: /steinernet.html` and ensure the server tries `$url.html` so that when `$url = "/steinernet"`, it will properly look for `/steinernet.html` and serve it with Content-Type: text/html. This is how it works for the Jekyll development server (`jekyll serve`) and for GitHub Pages.

Hope this helps!

**Comment by zfrenchee** [comment]
@parkr Do you mean `redirect_to` ?

**Comment by parkr** [comment]
@zfrenchee `redirect_to` should be left alone, but the file the `redirect_to` is in should end in `.html`, e.g. `/steinernet.html` would contain `redirect_to: <url>`.

**Comment by zfrenchee** [comment]
@parkr Hmm I'm confused about this. I tried what you suggest in your most recent comment, and it doesn't work. Navigating to fraenkel-lab.github.io/steinernet now still downloads a link, and navigating to fraenkel-lab.github.io/steinernet.html gives me a blank page on the jekyll site. 

The source is [here](https://github.com/fraenkel-lab/fraenkel-lab.github.io/blob/master/_pages/steinernet.html). Perhaps I'm messing this up with the permalink in the front matter?

**Comment by parkr** [comment]
@zfrenchee The problem is that it's not being output with an HTML extension to the filesystem. You didn't mention that you had set `permalink`. Try `permalink: /steinernet.html`.

**Comment by zfrenchee** [comment]
Thanks! That solves it for me!

**Comment by parkr** [comment]
You're welcome! Sorry for that little snafu.
