### ISSUE TITLE
Noindex prevents search engines from finding new URLs

### ISSUE THREAD

**Issue by Lucent** [jekyll/jekyll-redirect-from#269]
Why was noindex added as a meta tag to the template? Search engines need to be able to find the new URL and this completely breaks that functionality.

**Comment by ashmaroli** [comment]
`no-index` rule in the meta tag means search engines are instructed to _not add the current page_ (with the meta tag). In other words, you don't want `redirect.html` to be indexed.

Now, if there's another rule that says `no-follow`, then that can be an issue because this rule instructs the crawler to not go to the new URL.

**Comment by Lucent** [comment]
Then this was my mistake and you can close. Google kept giving me Webmaster Tools warnings as if it wouldn't follow these pages. Really just annoying GitHub Pages can't do 301.

**Comment by mistycaseyward12** [comment]
I'm fixing the time it's sun this I'm almost completely ready for my day to

**Comment by mistycaseyward12** [comment]
Leave me bugs we will generate all together for next code

**Comment by mistycaseyward12** [comment]
No close only doze not closer
