### ISSUE TITLE
'index' page generated rather than 'index.html'

### ISSUE THREAD

**Issue by alias1** [jekyll/jekyll-redirect-from#99]
With a url such as `redirect_from: post/10235539154/etcinitdblog-start/` i'm seeing the following generated (which at least in `jekyll serve` leads to an unviewable page) and cant figure out why.

```
/post/10235539154/etcinitdblog-start/index
```

**Comment by parkr** [comment]
@alias1 Which Jekyll version are you using?

**Comment by alias1** [comment]
3.1.1 off the top of my head

Sent from Outlook Mobile




On Thu, Feb 18, 2016 at 5:06 PM -0800, "Parker Moore" <notifications@github.com> wrote:












@alias1 Which Jekyll version are you using?

**Comment by yous** [comment]
As I think, this issue has caused by jekyll/jekyll#4160.

We're initializing `redirect_page` as following:

``` ruby
redirect_page = RedirectPage.new(site, site.source, "", "")
```

Then `JekyllRedirectFrom::Redirector` sets its page's `data['permalink']` to `alt_url`. `redirect_page.output_ext` actually calls `Jekyll::Renderer.new(site, self).output_ext`. So when `alt_url` ends with `'/'`, `output_ext` will return `document.extname`, which is an empty string.

**Comment by brandonb927** [comment]
I just realized my redirects are being generated in the same way, and `index` file instead of an `index.html` file is created in the redirect folder with any redirect using a trailing slash.

Jekyll 3.1.2, jekyll-redirect-from 0.9.1

**Comment by parkr** [comment]
@brandonb927 Could you give #96 a try for me? It should fix that.

**Comment by brandonb927** [comment]
Thanks @parkr, I'll give it a go this week. In the meantime I reverted our site back to jekyll 2.5.3, jekyll-redirect-from 0.8.0 which is the last known working state.

**Comment by marcgg** [comment]
Hello,

I'm having the same issue with jekyll 3.1.2 (`index` instead of `index.html`). I tried changing my Gemfile to:

```
gem "jekyll-redirect-from", github: "jekyll/jekyll-redirect-from", branch: "jekyll-3-drops"
```

... but it seems that the branch doesn't exist anymore. I noticed  that https://github.com/jekyll/jekyll-redirect-from/pull/96 merged the branch, so I just pointed to master and it worked:

```
gem 'jekyll-redirect-from', branch: "master", github: "jekyll/jekyll-redirect-from"
```

I'm not sure how stable master is though, so I might hold of before releasing the change and wait for the actual gem version release :)

Cheers

**Comment by jesmithiv** [comment]
I'm having the same issue -- i.e. getting an extension-less `index` for all redirects. Right now my workaround is to add `index.html` explicitly on the end of all `redirect_from` URLs. So rather than doing:

`redirect_from: /2015/12/08/foo/`

I'm doing:

`redirect_from: /2015/12/08/foo/index.html`

This achieves the intended result of the plugin, and I wonder if it's a more robust approach in general going forward since the goal of the `jekyll-redirect-from` is precisely this -- to create a folder structure with a single `index.html` in each.

**Comment by bturrubiates** [comment]
I think I'm having a similar problem with `redirect_to`.

If I want to redirect `x.html` -> `y.html`, then I could not have a `y.html` and specify in `x.html` `redirect_from: /url/for/y.html` and that seems to work correctly. If I look at the generated site, I have a file named `y.html` that serves a redirect to `x.html`.

I'd expect that a file called `y.html` that contains `redirect_to: /url/for/x.html` would behave the same. Instead, I get two generated files: `y.html` that has the contents of the file without the redirect and `y` that serves a redirect to `x.html`. I'd expect only one file named `y.html` that redirects to `x.html`. Is this a bug, or am I misunderstanding how this should work?

**Comment by drewda** [comment]
This seems to be working for me in https://github.com/jekyll/jekyll-redirect-from/releases/tag/v0.10.0

**Comment by alias1** [comment]
Can confirm, also working for me in `v0.10.0` :3 Thanks!

**Comment by michaelx** [comment]
With `Jekyll 3.1.6` and jekyll-redirect-from `0.10.0`index and index.html is generated for me. `index` contains the proper redirect, but `index.html` is empty (zero bytes).
